title: "The Bridge Knowledge Base"
description: "A Wikipedia-like site currently public"
remote_theme: "just-the-docs/just-the-docs" 
search_enabled: true
aux_links:
  "GitHub Repository": "https://github.com/thebridgelab/wiki-docs"
logo: "/images/logo.png" 
